# Generated by Django 4.2.7 on 2023-11-19 10:51

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutor',
            name='email',
            field=models.EmailField(default='bonnie', max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_first_name',
            field=models.CharField(default='gitonga', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tutor',
            name='tutor_last_name',
            field=models.CharField(default='gitonga', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tutor_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField()),
                ('enrollment_date', models.DateField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='student_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
